import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Alert } from '@/components/Alert'
import { Footer } from '@/components/Footer'

import { draftMode } from 'next/headers'
import { Container } from '@/components/Container'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { isEnabled } = draftMode()

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen">
          <Alert preview={isEnabled} />
          <main>
            <Container>{children}</Container>
          </main>
        </div>
        <Footer />
      </body>
    </html>
  )
}
