import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Alert } from '@/components/Alert'
import { Footer } from '@/components/Footer'
import { locales, Locales, defaultLocale } from '@/i18n'

import { draftMode } from 'next/headers'
import { Container } from '@/components/Container'

const inter = Inter({ subsets: ['latin'] })

export function generateStaticParams() {
  return process.env.ENABLE_I18N === 'true'
    ? locales.map((locale) => ({ locale }))
    : [{ locale: defaultLocale }]
}

// @todo: update metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LocaleLayoutProps = Readonly<{
  children: React.ReactNode
  params: { locale: Locales }
}>

export default function LocaleLayout({ children, params }: LocaleLayoutProps) {
  const { isEnabled } = draftMode()

  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <div className="min-h-screen">
          <Alert preview={isEnabled} />
          <main>
            <Container>{children}</Container>
          </main>
        </div>
        <Footer />
      </body>
    </html>
  )
}
